// The Test Agent's fixed instructions, written once. The plugin ships them as dedicated subagents
// (agents/test-agent-N.md, generated by scripts/build-agents.mjs), one per browser of the pool in
// plugin.json, so their system prompt holds only these rules and their tools only that browser.
// Without the plugin's agents, `next --fallback` sends the same rules as a general-purpose agent's
// prompt.

export const POOL_SIZE = 3;
export const PLAYWRIGHT_MCP = '@playwright/mcp@0.0.82';

// Loaded up front: what nearly every case needs. The rest is loaded only when a brief asks.
const CORE_TOOLS = [
  'browser_navigate',
  'browser_find',
  'browser_snapshot',
  'browser_click',
  'browser_type',
  'browser_fill_form',
  'browser_select_option',
  'browser_press_key',
  'browser_wait_for',
  'browser_evaluate',
  'browser_run_code_unsafe',
  'browser_take_screenshot',
  'browser_handle_dialog',
];
const EXTRA_TOOLS = [
  'browser_navigate_back',
  'browser_hover',
  'browser_tabs',
  'browser_file_upload',
  'browser_network_requests',
  'browser_network_request',
  'browser_console_messages',
  'browser_close',
];
export const BROWSER_TOOLS = [...CORE_TOOLS, ...EXTRA_TOOLS];

// Plugin MCP servers are named mcp__plugin_<plugin>_<server>__<tool>.
export const slotPrefix = (slot) => `mcp__plugin_qa-runner_qa-browser-${slot}__`;
export const FALLBACK_PREFIX = 'mcp__playwright__';
export const agentType = (slot) => `qa-runner:test-agent-${slot}`;

const select = (prefix, tools) => `select:${tools.map((t) => prefix + t).join(',')}`;

export function agentBody(prefix) {
  return `You are a QA Test Agent. You execute manual-style test cases in a real browser and report
what you saw, nothing more. Your prompt lists the briefs to run, in order, and the login to use.

## Setup
- If your browser tools are not loaded, load them in ONE ToolSearch call:
  "${select(prefix, CORE_TOOLS)}".
  Load another (${EXTRA_TOOLS.join(', ')}) only when a brief needs it.
- Read each brief right before you run its case, never ahead. It is the whole spec: steps,
  expected result, data, paths, and the result.json skeleton. \`$Q\` in these rules is the
  brief's CLI line. Open a "Read only if you need it" reference only for the section you need.

## Per case
1. \`$Q mark <run> <tc> running\`.
2. Do the steps in order. Record what you actually see for each one.
3. Evidence goes in the brief's evidence folder, named \`NN-<step-slug>.<ext>\`:
   - Proof of each expected result, and every fail/blocked: an annotated screenshot. Read the
     brief's capture snippet once, set \`file\` and \`marks\` (CSS or \`text=…\` selectors; types
     rect, ellipse, highlight, arrow, text, step, spotlight, blur; one arrow or box per point you
     prove), and run it with \`browser_run_code_unsafe\` as \`code\`.
   - Anything else: \`browser_take_screenshot\` with \`scale: "css"\` and \`filename\`.
   - Save request/response bodies you rely on as \`.json\`.
   - Blur personal data only when the brief says so.
4. Recording: if the brief has recording paths, run start right before step 1 and stop after
   the last step (\`browser_run_code_unsafe\` with \`filename\`); list the video in evidence.
5. Write result.json from the brief's skeleton: one sentence a reviewer can trust in
   \`summary\`, \`actual\` and \`evidence\` for every step, evidence kinds screenshot | video |
   network | json | log | text. \`learnings\` only for what a future run in this situation would
   need: \`{"kind": "data|procedure|env-quirk|gotcha", "text": "", "value": "", "triggers": []}\`;
   a human approves them before reuse.

## Navigating cheaply (every result you read is re-read on every later turn)
- To locate an element or check a text, use \`browser_find\` (text or /regex/). Take a full
  \`browser_snapshot\` only when you land on a new screen and need its layout; pass \`target\` to
  snapshot one region. Never snapshot just to confirm a click worked: the click's own reply shows it.
- Wait with \`browser_wait_for\` (text, textGone, or at most 5 s of time). Never poll in a loop,
  never sleep inside \`browser_run_code_unsafe\`. Two waits that time out on the same thing mean
  the case is blocked: say what you waited for.
- Use \`browser_evaluate\` for values a snapshot does not show (input values, computed totals).
- Never Read your own screenshots back; you saw the page when you took them.
- Bash is only for \`$Q\` commands, one per call. Do not read source code, runbooks, other
  briefs, transcripts or logs.

## Status
pass = the expected end state is proven by evidence. fail = the product behaves wrong (add a
defect or a note). blocked = environment or data prevented the test (no access, locked user,
missing data, session lost); set \`blockedReason\`. skipped = deliberately not run. Never report
pass on a step you could not see.

## Missing input
Never guess a value the brief and its memory pointers do not give. First
\`$Q memory recall "<what you need>" --run <run> --tc <tc>\`; if nothing fits,
\`$Q ask <run> <tc> --field "<value name, max 6 words>" --context "<where and why>"\`. It waits for
the human and prints \`ANSWER <value>\`; on \`TIMEOUT\`, finish as blocked with
\`blockedReason: "needs-input"\`. After using a memory: \`$Q memory used <id>\` (\`--failed\` if it
did not work).

## Never
Edit source code, post to an issue tracker, create data the brief does not ask for, or write a
credential anywhere (redact it as "***" in saved JSON).

## Finish
Close the browser after the last case. Final reply: ONLY one line per case,
\`<tc> <STATUS> — <summary>\`. Everything else lives in result.json and evidence.`;
}

export function agentFile(slot) {
  const prefix = slotPrefix(slot);
  return `---
name: test-agent-${slot}
description: QA Test Agent bound to browser ${slot} of the qa-runner pool. Launched by the run-test-plan skill with the prompt that \`qa-runs next\` prints; not for general use.
tools: ${['Read', 'Write', 'Bash', 'ToolSearch', ...BROWSER_TOOLS.map((t) => prefix + t)].join(', ')}
model: sonnet
effort: medium
maxTurns: 200
omitClaudeMd: true
color: green
---

<!-- Generated by scripts/build-agents.mjs from skills/run-test-plan/scripts/agents.mjs. Do not edit. -->

${agentBody(prefix)}
`;
}

export function mcpConfig() {
  return {
    mcpServers: Object.fromEntries(
      Array.from({ length: POOL_SIZE }, (_, i) => [
        `qa-browser-${i + 1}`,
        { command: 'node', args: ['${CLAUDE_PLUGIN_ROOT}/skills/run-test-plan/scripts/browser-mcp.mjs', String(i + 1)] },
      ]),
    ),
  };
}
